version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: dist
          command: npm run dist
      - store_artifacts:
          path: dist
          prefix: dist
